-- RiftSkin activation key system
-- Run in Supabase SQL editor (project: bvajoufrxxntivxghdgs)

create extension if not exists pgcrypto;

create table if not exists public.app_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.activation_keys (
  id bigint generated by default as identity primary key,
  code text not null unique,
  created_by uuid not null references auth.users(id) on delete cascade,
  created_for_email text,
  note text,
  max_uses integer not null default 1,
  used_count integer not null default 0,
  grant_days integer,
  expires_at timestamptz,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  constraint activation_keys_max_uses_check check (max_uses > 0),
  constraint activation_keys_used_count_check check (used_count >= 0),
  constraint activation_keys_grant_days_check check (grant_days is null or grant_days > 0)
);

create table if not exists public.key_redemptions (
  id bigint generated by default as identity primary key,
  key_id bigint not null references public.activation_keys(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  redeemed_at timestamptz not null default now(),
  unique (key_id, user_id)
);

create table if not exists public.user_access (
  user_id uuid primary key references auth.users(id) on delete cascade,
  source text not null default 'activation_key',
  granted_by_key_id bigint references public.activation_keys(id) on delete set null,
  granted_at timestamptz not null default now(),
  expires_at timestamptz,
  is_active boolean not null default true,
  constraint user_access_source_check check (source in ('activation_key', 'admin_grant'))
);

alter table public.app_admins enable row level security;
alter table public.activation_keys enable row level security;
alter table public.key_redemptions enable row level security;
alter table public.user_access enable row level security;

create or replace function public.is_app_admin(p_user uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(select 1 from public.app_admins where user_id = p_user);
$$;

create or replace function public.has_active_access(p_user uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(
    select 1
    from public.user_access ua
    where ua.user_id = p_user
      and ua.is_active = true
      and (ua.expires_at is null or ua.expires_at > now())
  );
$$;

create or replace function public.create_activation_key(
  p_for_email text default null,
  p_note text default null,
  p_max_uses integer default 1,
  p_valid_days integer default 30,
  p_grant_days integer default null
)
returns table(code text, expires_at timestamptz)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_raw text;
  v_code text;
  v_key_exp timestamptz;
begin
  if v_user is null then
    raise exception 'Not authenticated';
  end if;

  if not public.is_app_admin(v_user) then
    raise exception 'Only admins can create activation keys';
  end if;

  if p_max_uses is null or p_max_uses < 1 or p_max_uses > 500 then
    raise exception 'Invalid max uses (1-500)';
  end if;

  if p_valid_days is null or p_valid_days < 1 or p_valid_days > 3650 then
    raise exception 'Invalid key validity days (1-3650)';
  end if;

  if p_grant_days is not null and (p_grant_days < 1 or p_grant_days > 3650) then
    raise exception 'Invalid grant days (1-3650)';
  end if;

  loop
    v_raw := upper(encode(gen_random_bytes(8), 'hex'));
    v_code := substr(v_raw, 1, 4) || '-' || substr(v_raw, 5, 4) || '-' || substr(v_raw, 9, 4) || '-' || substr(v_raw, 13, 4);
    exit when not exists (select 1 from public.activation_keys where code = v_code);
  end loop;

  v_key_exp := now() + make_interval(days => p_valid_days);

  insert into public.activation_keys (
    code,
    created_by,
    created_for_email,
    note,
    max_uses,
    grant_days,
    expires_at
  ) values (
    v_code,
    v_user,
    nullif(trim(p_for_email), ''),
    nullif(trim(p_note), ''),
    p_max_uses,
    p_grant_days,
    v_key_exp
  );

  return query select v_code, v_key_exp;
end;
$$;

create or replace function public.redeem_activation_key(p_code text)
returns table(success boolean, message text, access_expires_at timestamptz)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_key public.activation_keys%rowtype;
  v_access_exp timestamptz;
begin
  if v_user is null then
    return query select false, 'not_authenticated', null::timestamptz;
    return;
  end if;

  select *
    into v_key
  from public.activation_keys
  where code = upper(trim(coalesce(p_code, '')))
  for update;

  if not found then
    return query select false, 'invalid_key', null::timestamptz;
    return;
  end if;

  if not v_key.is_active then
    return query select false, 'inactive_key', null::timestamptz;
    return;
  end if;

  if v_key.expires_at is not null and v_key.expires_at <= now() then
    return query select false, 'expired_key', null::timestamptz;
    return;
  end if;

  if exists(select 1 from public.key_redemptions kr where kr.key_id = v_key.id and kr.user_id = v_user) then
    return query select true, 'already_redeemed', (
      select ua.expires_at from public.user_access ua where ua.user_id = v_user
    );
    return;
  end if;

  if v_key.used_count >= v_key.max_uses then
    return query select false, 'key_limit_reached', null::timestamptz;
    return;
  end if;

  if v_key.grant_days is null then
    v_access_exp := null;
  else
    v_access_exp := now() + make_interval(days => v_key.grant_days);
  end if;

  insert into public.key_redemptions (key_id, user_id)
  values (v_key.id, v_user);

  update public.activation_keys
  set used_count = used_count + 1
  where id = v_key.id;

  insert into public.user_access (user_id, source, granted_by_key_id, granted_at, expires_at, is_active)
  values (v_user, 'activation_key', v_key.id, now(), v_access_exp, true)
  on conflict (user_id)
  do update
    set source = 'activation_key',
        granted_by_key_id = excluded.granted_by_key_id,
        granted_at = now(),
        expires_at = case
          when public.user_access.expires_at is null then null
          when excluded.expires_at is null then null
          else greatest(public.user_access.expires_at, excluded.expires_at)
        end,
        is_active = true;

  return query select true, 'redeemed', v_access_exp;
end;
$$;

-- Drop and recreate policies safely

do $$
begin
  -- app_admins
  if exists (select 1 from pg_policies where schemaname='public' and tablename='app_admins' and policyname='app_admins_select_own') then
    drop policy app_admins_select_own on public.app_admins;
  end if;
  if exists (select 1 from pg_policies where schemaname='public' and tablename='app_admins' and policyname='app_admins_admin_manage') then
    drop policy app_admins_admin_manage on public.app_admins;
  end if;

  create policy app_admins_select_own on public.app_admins
    for select using (auth.uid() = user_id or public.is_app_admin(auth.uid()));

  create policy app_admins_admin_manage on public.app_admins
    for all using (public.is_app_admin(auth.uid())) with check (public.is_app_admin(auth.uid()));

  -- activation_keys
  if exists (select 1 from pg_policies where schemaname='public' and tablename='activation_keys' and policyname='activation_keys_admin_all') then
    drop policy activation_keys_admin_all on public.activation_keys;
  end if;

  create policy activation_keys_admin_all on public.activation_keys
    for all using (public.is_app_admin(auth.uid())) with check (public.is_app_admin(auth.uid()));

  -- key_redemptions
  if exists (select 1 from pg_policies where schemaname='public' and tablename='key_redemptions' and policyname='key_redemptions_select_own') then
    drop policy key_redemptions_select_own on public.key_redemptions;
  end if;
  if exists (select 1 from pg_policies where schemaname='public' and tablename='key_redemptions' and policyname='key_redemptions_insert_own') then
    drop policy key_redemptions_insert_own on public.key_redemptions;
  end if;

  create policy key_redemptions_select_own on public.key_redemptions
    for select using (user_id = auth.uid() or public.is_app_admin(auth.uid()));

  create policy key_redemptions_insert_own on public.key_redemptions
    for insert with check (user_id = auth.uid() or public.is_app_admin(auth.uid()));

  -- user_access
  if exists (select 1 from pg_policies where schemaname='public' and tablename='user_access' and policyname='user_access_select_own') then
    drop policy user_access_select_own on public.user_access;
  end if;
  if exists (select 1 from pg_policies where schemaname='public' and tablename='user_access' and policyname='user_access_admin_manage') then
    drop policy user_access_admin_manage on public.user_access;
  end if;

  create policy user_access_select_own on public.user_access
    for select using (user_id = auth.uid() or public.is_app_admin(auth.uid()));

  create policy user_access_admin_manage on public.user_access
    for all using (public.is_app_admin(auth.uid())) with check (public.is_app_admin(auth.uid()));
end $$;

grant execute on function public.is_app_admin(uuid) to authenticated, anon;
grant execute on function public.has_active_access(uuid) to authenticated, anon;
grant execute on function public.create_activation_key(text, text, integer, integer, integer) to authenticated;
grant execute on function public.redeem_activation_key(text) to authenticated;

grant select on public.user_access to authenticated;
grant select on public.activation_keys to authenticated;

-- Bootstrap: set your own account as admin (replace EMAIL then run once)
-- insert into public.app_admins(user_id)
-- select id from auth.users where email = 'YOUR_EMAIL_HERE'
-- on conflict do nothing;
