
[functions.support-request]
enabled = true
verify_jwt = false
import_map = "./functions/support-request/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/support-request/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/support-request/*.html" ]

[functions.paddle-webhook]
enabled = true
verify_jwt = false
import_map = "./functions/paddle-webhook/deno.json"
entrypoint = "./functions/paddle-webhook/index.ts"

[functions.create-stripe-checkout-session]
enabled = true
verify_jwt = false
entrypoint = "./functions/create-stripe-checkout-session/index.ts"

[functions.create-stripe-portal-session]
enabled = true
verify_jwt = false
entrypoint = "./functions/create-stripe-portal-session/index.ts"

[functions.stripe-webhook]
enabled = true
verify_jwt = false
import_map = "./functions/stripe-webhook/deno.json"
entrypoint = "./functions/stripe-webhook/index.ts"

[functions.auth-send-confirmation]
enabled = true
verify_jwt = false
entrypoint = "./functions/auth-send-confirmation/index.ts"

[functions.auth-password-reset]
enabled = true
verify_jwt = false
entrypoint = "./functions/auth-password-reset/index.ts"

[functions.account-signup]
enabled = true
verify_jwt = false
entrypoint = "./functions/account-signup/index.ts"

[functions.desktop-activate-license]
enabled = true
verify_jwt = false
entrypoint = "./functions/desktop-activate-license/index.ts"

[functions.desktop-release-license]
enabled = true
verify_jwt = false
entrypoint = "./functions/desktop-release-license/index.ts"

[functions.delete-account]
enabled = true
verify_jwt = false
entrypoint = "./functions/delete-account/index.ts"

[functions.stripe-reconcile-subscription]
enabled = true
verify_jwt = false
entrypoint = "./functions/stripe-reconcile-subscription/index.ts"

[functions.account-subscription-summary]
enabled = true
verify_jwt = false
entrypoint = "./functions/account-subscription-summary/index.ts"

[functions.admin-dashboard]
enabled = true
verify_jwt = false
entrypoint = "./functions/admin-dashboard/index.ts"

[functions.public-download-redirect]
enabled = true
verify_jwt = false
entrypoint = "./functions/public-download-redirect/index.ts"
