import "jsr:@supabase/functions-js/edge-runtime.d.ts"
import { createClient } from "npm:@supabase/supabase-js@2"
import { renderEmailButton, renderEmailLayout } from "../_shared/email-template.ts"

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
}

function json(data: Record<string, unknown>, status = 200) {
  return new Response(JSON.stringify(data), {
    status,
    headers: {
      ...corsHeaders,
      "Content-Type": "application/json",
    },
  })
}

function normalizeEmail(value: unknown) {
  return String(value || "").trim().toLowerCase()
}

function normalizeRedirectTo(value: unknown) {
  const fallback = "https://riftskin.com/auth/callback"
  const raw = String(value || "").trim()
  if (!raw) return fallback
  try {
    const url = new URL(raw)
    if (url.origin !== "https://riftskin.com") return fallback
    if (url.pathname !== "/auth/callback") return fallback
    return url.toString()
  } catch (_error) {
    return fallback
  }
}

async function findUserByEmail(adminClient: any, email: string) {
  const normalized = normalizeEmail(email)
  let page = 1

  while (page <= 10) {
    const { data, error } = await adminClient.auth.admin.listUsers({
      page,
      perPage: 200,
    })

    if (error) throw error

    const users = Array.isArray(data?.users) ? data.users : []
    const match = users.find((user: any) => normalizeEmail(user.email) === normalized)
    if (match) return match
    if (users.length < 200) break
    page += 1
  }

  return null
}

async function sendAuthEmail(params: {
  toEmail: string
  subject: string
  html: string
  text: string
}) {
  const resendApiKey = Deno.env.get("RESEND_API_KEY")
  if (!resendApiKey) {
    return { sent: false, reason: "missing_resend_api_key" }
  }

  const fromEmail = Deno.env.get("SUPPORT_FROM_EMAIL")
    || Deno.env.get("BILLING_FROM_EMAIL")
    || "RIFTSKIN <no-reply@riftskin.com>"
  const replyToEmail = Deno.env.get("SUPPORT_TO_EMAIL") || "support@riftskin.com"

  const response = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${resendApiKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      from: fromEmail,
      to: [params.toEmail],
      reply_to: replyToEmail,
      subject: params.subject,
      html: params.html,
      text: params.text,
    }),
  })

  if (!response.ok) {
    const errorText = await response.text()
    throw new Error(`resend_error:${response.status}:${errorText}`)
  }

  const payload = await response.json().catch(() => ({}))
  return { sent: true, id: payload.id || null }
}

function buildConfirmationEmail(actionLink: string, mode: "signup" | "resend") {
  const title = mode === "signup" ? "Confirm your RIFTSKIN account" : "Your RIFTSKIN confirmation link"
  const lead = mode === "signup"
    ? "Your account has been created. Confirm your email to activate it and sign in normally."
    : "Here is a fresh confirmation link for your RIFTSKIN account."
  const previewText = mode === "signup"
    ? "Confirm your email to activate your RIFTSKIN account."
    : "A fresh confirmation link for your RIFTSKIN account is ready."

  const html = renderEmailLayout({
    previewText,
    eyebrow: "Account security",
    title,
    lead,
    bodyHtml: `
      <p style="margin:0 0 14px;">Use the button below to confirm your email address and finish activating your account.</p>
      <div style="margin:0 0 18px;">${renderEmailButton("Confirm my account", actionLink)}</div>
      <div style="margin:0 0 18px;padding:16px 18px;background:#0b1323;border:1px solid #22314d;border-radius:16px;color:#93a4bf;">
        After confirmation, return to the RIFTSKIN account page and sign in with your email and password.
      </div>
      <p style="margin:0;">If you did not request this account, you can safely ignore this email.</p>
    `,
    footerNote: "This confirmation link is generated by Supabase Auth and sent through RIFTSKIN mail delivery.",
  })

  const text = [
    title,
    "",
    "Use the link below to confirm your email address and activate your account:",
    actionLink,
    "",
    "After confirmation, return to the RIFTSKIN account page and sign in with your email and password.",
  ].join("\n")

  return {
    subject: title,
    html,
    text,
  }
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders })
  }

  if (req.method !== "POST") {
    return json({ error: "method_not_allowed" }, 405)
  }

  try {
    const supabaseUrl = Deno.env.get("SUPABASE_URL")
    const serviceRoleKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")
    if (!supabaseUrl || !serviceRoleKey) {
      return json({ error: "missing_supabase_env" }, 500)
    }

    const body = await req.json().catch(() => ({}))
    const email = normalizeEmail(body.email)
    const password = String(body.password || "")
    const redirectTo = normalizeRedirectTo(body.redirectTo)

    if (!email || !email.includes("@")) {
      return json({ error: "invalid_email" }, 400)
    }
    if (password.length < 8) {
      return json({ error: "invalid_password" }, 400)
    }

    const adminClient = createClient(supabaseUrl, serviceRoleKey, {
      auth: { persistSession: false },
    })

    const existingUser = await findUserByEmail(adminClient, email)
    if (existingUser?.email_confirmed_at) {
      return json({ error: "account_exists" }, 409)
    }

    const linkType = existingUser ? "magiclink" : "signup"
    const { data, error } = await adminClient.auth.admin.generateLink({
      type: linkType,
      email,
      password,
      options: {
        redirectTo,
      },
    })

    if (error) {
      return json({ error: "generate_link_failed", message: error.message }, 400)
    }

    const actionLink = data?.properties?.action_link || ""
    if (!actionLink) {
      return json({ error: "missing_action_link" }, 500)
    }

    const emailContent = buildConfirmationEmail(actionLink, existingUser ? "resend" : "signup")
    const mailResult = await sendAuthEmail({
      toEmail: email,
      subject: emailContent.subject,
      html: emailContent.html,
      text: emailContent.text,
    })

    return json({
      ok: true,
      sent: mailResult.sent,
      mode: existingUser ? "resend" : "signup",
    })
  } catch (error) {
    console.error("account-signup error", error)
    return json({
      error: "account_signup_failed",
      message: error instanceof Error ? error.message : "Unknown error",
    }, 500)
  }
})
