create table if not exists public.release_download_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default timezone('utc', now()),
  release_tag text not null,
  release_name text null,
  asset_name text not null,
  asset_download_url text not null,
  source_page text null,
  country_code text null,
  ip_address text null,
  forwarded_for text null,
  user_agent text null
);

create index if not exists release_download_events_release_tag_idx
  on public.release_download_events (release_tag);

create index if not exists release_download_events_country_code_idx
  on public.release_download_events (country_code);

create index if not exists release_download_events_ip_address_idx
  on public.release_download_events (ip_address);

create index if not exists release_download_events_created_at_idx
  on public.release_download_events (created_at desc);

alter table public.release_download_events enable row level security;

drop policy if exists release_download_events_admin_select on public.release_download_events;

create policy release_download_events_admin_select
  on public.release_download_events
  for select
  using (public.is_app_admin(auth.uid()));
