create table if not exists public.stripe_subscriptions (
  id bigint generated by default as identity primary key,
  stripe_subscription_id text not null unique,
  stripe_customer_id text,
  customer_email text not null,
  status text not null,
  product_id text,
  price_id text,
  current_period_starts_at timestamptz,
  current_period_ends_at timestamptz,
  canceled_at timestamptz,
  activated_at timestamptz,
  trialing_at timestamptz,
  paused_at timestamptz,
  activation_key_id bigint references public.activation_keys(id) on delete set null,
  last_event_id text,
  last_event_type text,
  last_event_at timestamptz,
  raw jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists stripe_subscriptions_customer_email_idx
  on public.stripe_subscriptions (lower(customer_email));
