create table if not exists public.paddle_subscriptions (
  id bigint generated by default as identity primary key,
  paddle_subscription_id text not null unique,
  paddle_customer_id text,
  customer_email text not null,
  status text not null,
  product_id text,
  price_id text,
  current_period_starts_at timestamptz,
  current_period_ends_at timestamptz,
  canceled_at timestamptz,
  activated_at timestamptz,
  trialing_at timestamptz,
  paused_at timestamptz,
  last_transaction_id text,
  activation_key_id bigint references public.activation_keys(id) on delete set null,
  notification_setting_id text,
  last_event_id text,
  last_event_type text,
  last_event_at timestamptz,
  raw jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists paddle_subscriptions_customer_email_idx
  on public.paddle_subscriptions (lower(customer_email));

create or replace function public.increment_activation_key_usage(p_key_id bigint)
returns void
language sql
security definer
set search_path = public
as $$
  update public.activation_keys
  set used_count = used_count + 1
  where id = p_key_id;
$$;

grant execute on function public.increment_activation_key_usage(bigint) to service_role;

create or replace function public.redeem_activation_key(p_code text)
returns table(success boolean, message text, access_expires_at timestamptz)
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_user uuid := auth.uid();
  v_user_email text;
  v_key public.activation_keys%rowtype;
  v_access_exp timestamptz;
  v_existing_exp timestamptz;
begin
  if v_user is null then
    return query select false, 'not_authenticated', null::timestamptz;
    return;
  end if;

  select *
    into v_key
  from public.activation_keys
  where code = upper(trim(coalesce(p_code, '')))
  for update;

  if not found then
    return query select false, 'invalid_key', null::timestamptz;
    return;
  end if;

  if not v_key.is_active then
    return query select false, 'inactive_key', null::timestamptz;
    return;
  end if;

  select u.email into v_user_email
  from auth.users u
  where u.id = v_user;

  if v_key.created_for_email is not null
     and coalesce(lower(trim(v_user_email)), '') <> lower(trim(v_key.created_for_email)) then
    return query select false, 'key_reserved_for_other_email', null::timestamptz;
    return;
  end if;

  if v_key.expires_at is not null and v_key.expires_at <= now() then
    return query select false, 'expired_key', null::timestamptz;
    return;
  end if;

  if exists(select 1 from public.key_redemptions kr where kr.key_id = v_key.id and kr.user_id = v_user) then
    select ua.expires_at
      into v_existing_exp
    from public.user_access ua
    where ua.user_id = v_user;

    if v_key.note like '[paddle-subscription:%' and (v_existing_exp is null or v_key.expires_at is null or v_key.expires_at > v_existing_exp) then
      update public.user_access
      set granted_by_key_id = v_key.id,
          granted_at = now(),
          expires_at = v_key.expires_at,
          is_active = true
      where user_id = v_user;

      return query select true, 'already_redeemed', v_key.expires_at;
      return;
    end if;

    return query select true, 'already_redeemed', v_existing_exp;
    return;
  end if;

  if v_key.used_count >= v_key.max_uses then
    return query select false, 'key_limit_reached', null::timestamptz;
    return;
  end if;

  if v_key.note like '[paddle-subscription:%' then
    v_access_exp := v_key.expires_at;
  elsif v_key.grant_months is not null then
    v_access_exp := now() + make_interval(months => v_key.grant_months);
  elsif v_key.grant_days is not null then
    v_access_exp := now() + make_interval(days => v_key.grant_days);
  else
    v_access_exp := null;
  end if;

  insert into public.key_redemptions (key_id, user_id)
  values (v_key.id, v_user);

  perform public.increment_activation_key_usage(v_key.id);

  insert into public.user_access (user_id, source, granted_by_key_id, granted_at, expires_at, is_active)
  values (v_user, 'activation_key', v_key.id, now(), v_access_exp, true)
  on conflict (user_id)
  do update
    set source = 'activation_key',
        granted_by_key_id = excluded.granted_by_key_id,
        granted_at = now(),
        expires_at = case
          when public.user_access.expires_at is null then null
          when excluded.expires_at is null then null
          else greatest(public.user_access.expires_at, excluded.expires_at)
        end,
        is_active = true;

  return query select true, 'redeemed', v_access_exp;
end;
$$;

create or replace function public.attach_activation_key_to_user(
  p_code text,
  p_user_email text
)
returns table(success boolean, message text, access_expires_at timestamptz)
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_admin uuid := auth.uid();
  v_target_user uuid;
  v_target_email text;
  v_key public.activation_keys%rowtype;
  v_access_exp timestamptz;
  v_existing_exp timestamptz;
begin
  if v_admin is null then
    return query select false, 'not_authenticated', null::timestamptz;
    return;
  end if;

  if not public.is_app_admin(v_admin) then
    return query select false, 'not_admin', null::timestamptz;
    return;
  end if;

  v_target_email := lower(trim(coalesce(p_user_email, '')));
  if v_target_email = '' then
    return query select false, 'user_not_found', null::timestamptz;
    return;
  end if;

  select u.id
    into v_target_user
  from auth.users u
  where lower(u.email) = v_target_email
  limit 1;

  if v_target_user is null then
    return query select false, 'user_not_found', null::timestamptz;
    return;
  end if;

  select *
    into v_key
  from public.activation_keys
  where code = upper(trim(coalesce(p_code, '')))
  for update;

  if not found then
    return query select false, 'invalid_key', null::timestamptz;
    return;
  end if;

  if not v_key.is_active then
    return query select false, 'inactive_key', null::timestamptz;
    return;
  end if;

  if v_key.expires_at is not null and v_key.expires_at <= now() then
    return query select false, 'expired_key', null::timestamptz;
    return;
  end if;

  if v_key.created_for_email is not null
     and lower(trim(v_key.created_for_email)) <> v_target_email then
    return query select false, 'email_mismatch', null::timestamptz;
    return;
  end if;

  if exists(select 1 from public.key_redemptions kr where kr.key_id = v_key.id and kr.user_id = v_target_user) then
    select ua.expires_at
      into v_existing_exp
    from public.user_access ua
    where ua.user_id = v_target_user;

    if v_key.note like '[paddle-subscription:%' and (v_existing_exp is null or v_key.expires_at is null or v_key.expires_at > v_existing_exp) then
      update public.user_access
      set granted_by_key_id = v_key.id,
          granted_at = now(),
          expires_at = v_key.expires_at,
          is_active = true
      where user_id = v_target_user;

      return query select true, 'already_redeemed', v_key.expires_at;
      return;
    end if;

    return query select true, 'already_redeemed', v_existing_exp;
    return;
  end if;

  if v_key.used_count >= v_key.max_uses then
    return query select false, 'key_limit_reached', null::timestamptz;
    return;
  end if;

  if v_key.note like '[paddle-subscription:%' then
    v_access_exp := v_key.expires_at;
  elsif v_key.grant_months is not null then
    v_access_exp := now() + make_interval(months => v_key.grant_months);
  elsif v_key.grant_days is not null then
    v_access_exp := now() + make_interval(days => v_key.grant_days);
  else
    v_access_exp := null;
  end if;

  insert into public.key_redemptions (key_id, user_id)
  values (v_key.id, v_target_user);

  perform public.increment_activation_key_usage(v_key.id);

  insert into public.user_access (user_id, source, granted_by_key_id, granted_at, expires_at, is_active)
  values (v_target_user, 'activation_key', v_key.id, now(), v_access_exp, true)
  on conflict (user_id)
  do update
    set source = 'activation_key',
        granted_by_key_id = excluded.granted_by_key_id,
        granted_at = now(),
        expires_at = case
          when public.user_access.expires_at is null then null
          when excluded.expires_at is null then null
          else greatest(public.user_access.expires_at, excluded.expires_at)
        end,
        is_active = true;

  return query select true, 'attached', v_access_exp;
end;
$$;
